# Generated by Django 4.2.5 on 2024-03-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progsbase', '0002_lang_tag_prog_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='progs',
        ),
        migrations.AddField(
            model_name='prog',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags_of_prog', to='progsbase.tag', verbose_name='Тэги'),
        ),
    ]
