# Generated by Django 4.2.5 on 2024-03-24 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progsbase', '0003_remove_tag_progs_prog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='prog',
            name='text',
            field=models.FileField(blank=True, default=None, null=True, upload_to='progs/text/', verbose_name='Текст программы'),
        ),
        migrations.CreateModel(
            name='ProgImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('prog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='progsbase.prog', verbose_name='Программа')),
            ],
        ),
    ]
