# Generated by Django 4.2.5 on 2024-03-25 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progsbase', '0004_prog_text_progimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progimage',
            name='image',
            field=models.ImageField(default=None, upload_to='progs/pic/', verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='ProgLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('prog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='progsbase.prog', verbose_name='Программа')),
            ],
        ),
    ]
