# Generated by Django 4.2.5 on 2024-03-25 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progsbase', '0005_alter_progimage_image_proglink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progimage',
            options={'verbose_name': 'Изображение программы', 'verbose_name_plural': 'Изображения программы'},
        ),
        migrations.AlterModelOptions(
            name='proglink',
            options={'verbose_name': 'Ссылка программы', 'verbose_name_plural': 'Ссылки программы'},
        ),
        migrations.AlterField(
            model_name='lang',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Язык программирования'),
        ),
        migrations.AlterField(
            model_name='progimage',
            name='image',
            field=models.ImageField(upload_to='progs/pic/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='progimage',
            name='prog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='progsbase.prog', verbose_name='Программа'),
        ),
    ]
