# Generated by Django 4.2.5 on 2024-03-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progsbase', '0006_alter_progimage_options_alter_proglink_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progimage',
            name='image',
            field=models.ImageField(upload_to='progsbase/pic/', verbose_name='Изображение'),
        ),
    ]
