# Generated by Django 4.2.5 on 2024-03-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progsbase', '0007_alter_progimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prog',
            name='text',
            field=models.FileField(blank=True, default=None, null=True, upload_to='progsbase/text/', verbose_name='Текст программы'),
        ),
    ]
