# Generated by Django 4.2.5 on 2024-03-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progsbase', '0008_alter_prog_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='progimage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='proglink',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
