# Generated by Django 4.2.5 on 2024-03-28 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progsbase', '0011_alter_lang_slug_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prog',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='langs', to='progsbase.lang', verbose_name='Язык программирования'),
        ),
    ]
