# Generated by Django 4.2.5 on 2023-11-20 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Набор')),
            ],
            options={
                'verbose_name': 'Набор',
                'verbose_name_plural': 'Наборы',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='word',
            name='word_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='words.wordset', verbose_name='Набор'),
        ),
    ]
