# Generated by Django 4.2.5 on 2023-11-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_wordset_word_word_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='word_set',
        ),
        migrations.AddField(
            model_name='word',
            name='word_sets',
            field=models.ManyToManyField(blank=True, null=True, related_name='word_sets', to='words.wordset', verbose_name='Набор'),
        ),
    ]
