# Generated by Django 4.2.5 on 2023-11-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_remove_word_word_set_word_word_sets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='word_sets',
        ),
        migrations.AddField(
            model_name='wordset',
            name='words',
            field=models.ManyToManyField(blank=True, null=True, related_name='words', to='words.word', verbose_name='Слова'),
        ),
    ]
