# Generated by Django 4.2.5 on 2023-11-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_remove_word_word_sets_wordset_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordset',
            name='words',
            field=models.ManyToManyField(blank=True, null=True, related_name='words_in_set', to='words.word', verbose_name='Слова'),
        ),
    ]
