# Generated by Django 4.2.5 on 2023-09-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddIndex(
            model_name='tasks',
            index=models.Index(fields=['-time_create'], name='tasks_tasks_time_cr_39769d_idx'),
        ),
    ]
