# Generated by Django 4.2.5 on 2023-09-27 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tasks_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('status', models.IntegerField(choices=[(0, 'Черновик'), (1, 'Новая'), (2, 'Выполняется'), (3, 'Выполнена')], default=0)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('time_deadline', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.category')),
            ],
            options={
                'verbose_name_plural': 'tasks',
                'ordering': ['-time_create'],
            },
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['-time_create'], name='tasks_task_time_cr_c553fd_idx'),
        ),
    ]
