# Generated by Django 4.2.5 on 2023-10-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_category_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_deadline',
            field=models.DateTimeField(blank=True, verbose_name='Срок выполнения'),
        ),
    ]
