# Generated by Django 4.2.5 on 2023-10-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_time_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения'),
        ),
    ]
